export const Columns = [
  {
    field: 'app_id',
    minWidth: 110,
    width: 110,
  },
  {
    field: 'vehicle',
  },
  {field: 'dealer'},
  {
    field: 'st',
    minWidth: 60,
  },
  {
    field: 'tz',
    minWidth: 60,
  },
  {field: 'applicant'},
  {
    field: 'tier',
    minWidth: 70,
  },
  {
    field: 'term',
    minWidth: 80,
  },
  {
    field: 'req_amt',
    minWidth: 100,
  },
  {field: 'submitted_date'},
  {field: 'assigned'},
  {
    field: 'status',
    minWidth: 70,
    width: 90,
  },
];

export const ColumnsPin = [
  {
    field: 'app_id',
    pinned: 'left',
    minWidth: 70,
    width: 110,
  },
  {
    field: 'vehicle',
    pinned: 'left',
  },
  {field: 'dealer'},
  {
    field: 'st',
    minWidth: 60,
  },
  {
    field: 'tz',
    minWidth: 60,
  },
  {field: 'applicant'},
  {
    field: 'tier',
    minWidth: 70,
  },
  {
    field: 'term',
    minWidth: 80,
  },
  {
    field: 'req_amt',
    minWidth: 100,
  },
  {field: 'submitted_date'},
  {field: 'assigned'},
  {
    field: 'status',
    pinned: 'right',
    minWidth: 70,
    width: 90,
  },
];

export const RowData = [
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
];
