export const Columns = [
  {field: 'app_id'},
  {field: 'dealer'},
  {field: 'st'},
  {field: 'tz'},
  {field: 'applicant'},
  {field: 'vehicle'},
  {field: 'tier'},
  {field: 'term'},
  {field: 'req_amt'},
  {field: 'status'},
  {field: 'submitted_date'},
  {field: 'assigned'},
];

export const RowData = [
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
  {
    app_id: '60011564',
    dealer: 'SAN DIEGO CARS',
    st: 'CA',
    tz: 'P',
    applicant: 'SMITH',
    vehicle: '2019 NISSAN ALTIMA',
    tier: '2',
    term: '24',
    req_amt: '$21.937',
    status: 'NEW',
    submitted_date: '10/15 09:33A',
    assigned: 'BDRAPER',
  },
];
